from .template import Block
from .random import RandomBlock
from .range import RangeBlock
from .fiftyfifty import FiftyFiftyBlock
from .shortcutredirect import ShortCutRedirectBlock
from .strictvariablegetter import StrictVariableGetterBlock
from .loosevariablegetter import LooseVariableGetterBlock
from .math import MathBlock
from .assign import AssignmentBlock
from .strf import StrfBlock